# Generated by Django 4.1.2 on 2022-10-07 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_customers_date_created_customers_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customers',
            old_name='Image',
            new_name='image',
        ),
    ]
